# Educational Evaluation Configuration
# Simplified configuration for educational trajectory estimation

evaluation:
  name: "Educational Trajectory Estimation"
  output_dir: output/educational
  parallel_jobs: 1  # Sequential for clarity
  generate_plots: true
  save_intermediate: true

# Resource limits
resources:
  timeout_minutes: 5  # 5 minutes per estimation
  max_memory_gb: 2

# Educational datasets - will auto-generate if not present
datasets:
  simulated:
    generate_if_missing: true  # Auto-generate if data doesn't exist
    cache_dir: data/trajectories  # Where to save/load pre-generated data
    types:
      - name: circle_easy
        config: config/simulation/circle_easy.yaml
        description: Simple circle with low noise
      - name: circle_medium
        config: config/simulation/circle_medium.yaml
        description: Circle with medium noise
      - name: figure8_easy
        config: config/simulation/figure8_easy.yaml
        description: Figure-8 with low noise

# Estimator configurations
estimators:
  ekf:
    enabled: true
    config:
      use_preintegrated_imu: true
      use_keyframes_only: true
      initial_position_std: 0.1
      initial_velocity_std: 0.1
      gravity_magnitude: 9.81
  
  gtsam-ekf:
    enabled: true
    config:
      use_preintegrated_imu: true
      use_keyframes_only: true
      imu_params:
        accel_noise_sigma: 0.01
        gyro_noise_sigma: 0.001
        accel_bias_rw_sigma: 0.001
        gyro_bias_rw_sigma: 0.0001

# Dashboard configuration
dashboard:
  title: "Educational SLAM Results"
  sections:
    - type: trajectory_comparison
      title: "Trajectory Comparison"
    - type: error_metrics
      title: "Error Metrics"
    - type: runtime_performance
      title: "Performance"

# Logging configuration
logging:
  level: "INFO"
  console: true
  file: "educational.log"