# Educational Evaluation Configuration
# Simplified configuration for educational trajectory estimation

evaluation:
  output_dir: output/educational
  parallel_jobs: 1  # Sequential for clarity
  generate_plots: true
  save_intermediate: true

# Educational datasets - will auto-generate if not present
datasets:
  simulated:
    generate_if_missing: true  # Auto-generate if data doesn't exist
    cache_dir: data/trajectories  # Where to save/load pre-generated data
    types:
      - name: circle_easy
        config: config/simulation/circle_easy.yaml
        description: Simple circle with low noise
      - name: circle_medium
        config: config/simulation/circle_medium.yaml
        description: Circle with medium noise
      - name: figure8_easy
        config: config/simulation/figure8_easy.yaml
        description: Figure-8 with low noise
      - name: figure8_hard
        config: config/simulation/figure8_hard.yaml
        description: Figure-8 with high noise
      - name: spiral_medium
        config: config/simulation/spiral_medium.yaml
        description: Spiral with medium noise

# Estimator configurations
estimators:
  ekf:
    enabled: true
    config:
      use_preintegrated_imu: true
      use_keyframes_only: true
      initial_position_std: 0.1
      initial_velocity_std: 0.1
      gravity_magnitude: 9.81
  
  swba:
    enabled: true
    config:
      use_preintegrated_imu: true
      use_simulation_keyframes: true
      window_size: 10
      optimization_iterations: 5
  
  srif:
    enabled: true
    config:
      use_preintegrated_imu: true
      use_keyframes_only: true
      initial_information: 100.0

# Dashboard configuration
dashboard:
  enabled: true
  template: educational  # Use educational template
  sections:
    - summary_table
    - trajectory_plots
    - error_plots
    - performance_comparison
  
  # Specific plots for education
  plots:
    - type: trajectory_3d
      title: "3D Trajectory Comparison"
    - type: ate_timeline
      title: "Absolute Trajectory Error Over Time"
    - type: runtime_comparison
      title: "Algorithm Performance Comparison"
    - type: error_boxplot
      title: "Error Distribution by Algorithm"

# Metrics to compute
metrics:
  trajectory:
    - ate_rmse
    - ate_mean
    - rpe_trans_rmse
    - rpe_rot_rmse
  
  performance:
    - runtime_ms
    - memory_mb
    - num_keyframes
  
  consistency:
    - nees_mean
    - nees_chi2_percentage

# Report settings
reporting:
  format: html
  include_latex: false  # Keep it simple
  include_code_snippets: true  # Show algorithm snippets
  comparison_table: true
  statistical_tests: true