type: "ekf"
ekf:
  pixel_noise_std: 1.0
  chi2_threshold: 5.991
  innovation_threshold: 3.0
  max_iterations: 5
  
  # Initial uncertainties
  initial_position_std: 0.1
  initial_orientation_std: 0.01
  initial_velocity_std: 0.1
  initial_accel_bias_std: 0.01
  initial_gyro_bias_std: 0.001
  
  # Process noise
  accel_noise_density: 0.01
  gyro_noise_density: 0.001
  accel_bias_random_walk: 0.001
  gyro_bias_random_walk: 0.0001
  
  # Integration
  integration_method: "euler"
  gravity_magnitude: 9.81