# GTSAM EKF (ISAM2) Estimator Configuration
# Uses incremental smoothing for EKF-like behavior

gtsam_ekf:
  estimator_type: gtsam_ekf
  max_landmarks: 1000
  max_iterations: 100
  convergence_threshold: 1.0e-6
  outlier_threshold: 5.0
  enable_marginalization: false  # ISAM2 handles this internally
  marginalization_window: 10
  verbose: false
  save_intermediate: false
  seed: 42
  
  # ISAM2 specific parameters
  isam2:
    relinearize_threshold: 0.1
    relinearize_skip: 10
    cache_linearized_factors: true
    enable_partial_relinearization: false

  # Noise model parameters (standard deviations)
  noise:
    prior_pose_translation: 0.1  # meters
    prior_pose_rotation: 0.1     # radians
    prior_velocity: 0.1           # m/s
    prior_bias_acc: 0.01          # m/s^2
    prior_bias_gyro: 0.001        # rad/s
    
    imu_factor_translation: 0.1
    imu_factor_rotation: 0.1
    imu_factor_velocity: 0.1