type: "srif"
srif:
  # Numerical parameters
  qr_threshold: 1.0e-10
  adaptive_threshold: true
  
  # Initial uncertainties
  initial_position_std: 0.1
  initial_velocity_std: 0.1
  initial_orientation_std: 0.01
  initial_bias_std: 0.01
  initial_information_scale: 10.0
  
  # Process noise
  accel_noise_std: 0.1
  gyro_noise_std: 0.01
  accel_bias_noise_std: 0.001
  gyro_bias_noise_std: 0.0001
  
  # Integration
  integration_method: "rk4"
  
  # Features
  use_preintegrated_imu: false
  use_keyframes_only: false