# Circle Easy - Simple trajectory for beginners
name: circle_easy
description: Simple circle trajectory with low noise - perfect for beginners

# Trajectory configuration
trajectory:
  type: circle
  duration: 20.0
  frequency: 100.0  # Hz
  radius: 5.0
  velocity: 1.0

# Sensor configuration
sensors:
  imu:
    frequency: 200.0  # Hz
    noise:
      accelerometer_noise_density: 0.0001  # Very low noise
      gyroscope_noise_density: 0.00001
      accelerometer_random_walk: 0.00001
      gyroscope_random_walk: 0.000001
  
  camera:
    frequency: 10.0  # Hz
    noise:
      pixel_noise: 0.01  # Very low pixel noise
    calibration:
      fx: 500.0
      fy: 500.0
      cx: 320.0
      cy: 240.0
      width: 640
      height: 480

# Landmark configuration
landmarks:
  num_landmarks: 50
  x_range: [-10.0, 10.0]
  y_range: [-10.0, 10.0]
  z_range: [0.0, 5.0]

# Keyframe selection
keyframes:
  strategy: fixed_interval
  interval: 10  # Every 10th camera frame

# IMU Preintegration
preintegration:
  enabled: true

# Random seed for reproducibility
seed: 42

# Output configuration
output:
  save_raw_imu: false  # Don't save raw IMU to reduce file size
  save_preintegrated: true
  save_visualization: false