# Figure-8 Hard - Stress testing with high noise
name: figure8_hard
description: Figure-8 trajectory with high noise - stress testing

# Trajectory configuration
trajectory:
  type: figure8
  duration: 20.0
  frequency: 100.0  # Hz
  scale_x: 3.0
  scale_y: 2.0
  height: 1.5
  velocity: 1.0

# Sensor configuration
sensors:
  imu:
    frequency: 200.0  # Hz
    noise:
      accelerometer_noise_density: 0.005  # High noise
      gyroscope_noise_density: 0.0005
      accelerometer_random_walk: 0.0005
      gyroscope_random_walk: 0.00005
  
  camera:
    frequency: 10.0  # Hz
    noise:
      pixel_noise: 0.5  # High pixel noise
    calibration:
      fx: 500.0
      fy: 500.0
      cx: 320.0
      cy: 240.0
      width: 640
      height: 480

# Landmark configuration
landmarks:
  num_landmarks: 50
  x_range: [-10.0, 10.0]
  y_range: [-10.0, 10.0]
  z_range: [0.0, 5.0]

# Keyframe selection
keyframes:
  strategy: fixed_interval
  interval: 30  # Every 30th camera frame (sparse keyframes)

# IMU Preintegration
preintegration:
  enabled: true

# Random seed for reproducibility
seed: 45

# Output configuration
output:
  save_raw_imu: false
  save_preintegrated: true
  save_visualization: false