# Figure-8 Easy - Motion complexity with low noise
name: figure8_easy
description: Figure-8 trajectory with low noise - introduces motion complexity

# Trajectory configuration
trajectory:
  type: figure8
  duration: 35.0  # Increased for slower, more realistic motion
  frequency: 100.0  # Hz
  scale_x: 2.5  # Slightly smaller scale
  scale_y: 1.5  # Slightly smaller scale
  height: 1.5
  velocity: 0.7  # Slower velocity to prevent drift

# Sensor configuration
sensors:
  imu:
    frequency: 200.0  # Hz
    noise:
      accelerometer_noise_density: 0.0001  # Low noise
      gyroscope_noise_density: 0.00001
      accelerometer_random_walk: 0.00001
      gyroscope_random_walk: 0.000001
  
  camera:
    frequency: 10.0  # Hz
    noise:
      pixel_noise: 0.01  # Low pixel noise
    calibration:
      fx: 500.0
      fy: 500.0
      cx: 320.0
      cy: 240.0
      width: 640
      height: 480

# Landmark configuration
landmarks:
  num_landmarks: 50
  x_range: [-10.0, 10.0]
  y_range: [-10.0, 10.0]
  z_range: [0.0, 5.0]

# Keyframe selection
keyframes:
  strategy: fixed_interval
  interval: 15  # Every 15th camera frame

# IMU Preintegration
preintegration:
  enabled: true

# Random seed for reproducibility
seed: 44

# Output configuration
output:
  save_raw_imu: false
  save_preintegrated: true
  save_visualization: false