# Spiral Medium - Non-planar motion
name: spiral_medium
description: Spiral trajectory with medium noise - non-planar motion

# Trajectory configuration
trajectory:
  type: spiral
  duration: 35.0  # Increased for slower, more realistic motion
  frequency: 100.0  # Hz
  initial_radius: 0.5
  final_radius: 2.5  # Slightly smaller final radius
  initial_height: 0.5
  final_height: 2.5  # Slightly lower final height
  velocity: 0.75  # Slower velocity to prevent drift

# Sensor configuration
sensors:
  imu:
    frequency: 200.0  # Hz
    noise:
      accelerometer_noise_density: 0.001  # Medium noise
      gyroscope_noise_density: 0.0001
      accelerometer_random_walk: 0.0001
      gyroscope_random_walk: 0.00001
  
  camera:
    frequency: 10.0  # Hz
    noise:
      pixel_noise: 0.1  # Medium pixel noise
    calibration:
      fx: 500.0
      fy: 500.0
      cx: 320.0
      cy: 240.0
      width: 640
      height: 480

# Landmark configuration
landmarks:
  num_landmarks: 50
  x_range: [-10.0, 10.0]
  y_range: [-10.0, 10.0]
  z_range: [0.0, 5.0]

# Keyframe selection
keyframes:
  strategy: fixed_interval
  interval: 25  # Every 25th camera frame

# IMU Preintegration
preintegration:
  enabled: true

# Random seed for reproducibility
seed: 46

# Output configuration
output:
  save_raw_imu: false
  save_preintegrated: true
  save_visualization: false